version: 2
enable-beta-ecosystems: true

multi-ecosystem-groups:
  ci:
    schedule:
      interval: "weekly"
  dev:
    schedule:
      interval: "weekly"

updates:
  - package-ecosystem: "uv"
    directory: "/"
    multi-ecosystem-group: "dev"
    patterns: ["*"]
    ignore:
      - dependency-name: "aiohttp"
      - dependency-name: "orjson"
      - dependency-name: "yarl"

  - package-ecosystem: "github-actions"
    directory: "/"
    multi-ecosystem-group: "ci"
    patterns: ["*"]

  - package-ecosystem: "pre-commit"
    directory: "/"
    multi-ecosystem-group: "dev"
    patterns: ["*"]
