change-template: "- #$NUMBER $TITLE @$AUTHOR"
sort-direction: ascending

categories:
  - title: ":boom: Breaking Changes"
    label: "breaking-change"

  - title: ":sparkles: New Features"
    label: "new-feature"

  - title: ":zap: Performance"
    label: "performance"

  - title: ":recycle: Refactor"
    label: "refactor"

  - title: ":green_heart: CI"
    label: "ci"

  - title: ":bug: Bug Fixes"
    label: "bugfix"

  - title: ":white_check_mark: Tests"
    label: "tests"

  - title: ":arrow_up: Dependency Updates"
    label: "dependencies"
    collapse-after: 1

include-labels:
  - "breaking-change"
  - "performance"
  - "refactor"
  - "new-feature"
  - "bugfix"
  - "dependencies"
  - "tests"
  - "ci"

template: |
  $CHANGES
