name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v6.0.0
        with:
          enable-cache: true
          python-version: 3.13

      - name: Set package version
        run: |
          version="${{ github.event.release.tag_name }}"
          sed -i "s/^version = \".*\"/version = \"${version}\"/" pyproject.toml

      - name: Build package
        run: uv build

      - name: Publish release to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.4
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
